services:
  - type: web
    name: muslim-nikah
    env: python
    buildCommand: chmod +x render_build.sh && ./render_build.sh
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
    plan: free 