services:
  - type: web
    name: muslim-nikah
    env: python
    buildCommand: chmod +x render_build.sh && ./render_build.sh
    startCommand: gunicorn wsgi_app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: PIP_EXTRA_INDEX_URL
        value: https://pypi.org/simple/
    plan: free 